[[headers]]
for = "/backoffice"
[headers.values]
  Basic-Auth = "admin 1005"

[[headers]]
for = "/backoffice/*"
[headers.values]
  Basic-Auth = "admin 1005"

[build]
publish = "."
command = "npm run generate-products && npm run build"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
