backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple

collections:
  - name: "products"
    label: "Produits"
    file: "data/products.json"
    fields:
      - label: "Produits"
        name: "items"
        widget: "list"
        summary: "{{fields.name}} – {{fields.price}}€"
        fields:
          - { label: "Nom", name: "name", widget: "string" }
          - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", min: 0, step: 0.01 }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: "Image (URL)", name: "image", widget: "string", required: false }
          - { label: "Vidéo (URL .mp4)", name: "video", widget: "string", required: false }
          - { label: "Badge", name: "badge", widget: "string", required: false }
          - { label: "Ordre", name: "order", widget: "number", value_type: "int", min: 0, default: 0 }
          - { label: "Publié ?", name: "published", widget: "boolean", default: true }
